replicaCount: 2

image:
  repository: aiops-inference
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  drift_threshold: "3.0"
  log_level: "INFO"

prometheus:
  enabled: true
  port: 8000
  path: /metrics
